GET http://localhost:8080/produtos

###

GET http://localhost:8080/produto/2
authorization: 519f40287c77878f3f0d6b1ac9e643306bfc3ce0f7dbeb67a2c48fdf224a98ca

###

DELETE http://localhost:8080/produto/3 HTTP/1.1
authorization: 519f40287c77878f3f0d6b1ac9e643306bfc3ce0f7dbeb67a2c48fdf224a98ca

###

POST http://localhost:8080/produto HTTP/1.1 
Content-Type: application/json
authorization: 519f40287c77878f3f0d6b1ac9e643306bfc3ce0f7dbeb67a2c48fdf224a98ca

{
    "id": 5,
    "nome": "Pão na chapa",
    "preco": 6.50,
    "quantidade": 1,
    "categoria": "Comida",
    "fabricante": {
      "nomef": "Padaria ABC",
      "endereco": "Avenida dos Andradas, 200 "
    }
}


###

PUT http://localhost:8080/produto/1
Content-Type: application/json
authorization: 519f40287c77878f3f0d6b1ac9e643306bfc3ce0f7dbeb67a2c48fdf224a98ca

{
    "id": 1,
    "nome": "Pão na chapa",
    "preco": 5.50,
    "quantidade": 1,
    "categoria": "Comida",
    "fabricante": {
      "nomef": "Padaria ABC",
      "endereco": "Avenida dos Andradas, 200 "
    }
}

###
